# Generated by Django 2.0.2 on 2018-05-18 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('librosoci', '0027_auto_20180517_2030'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oggetto', models.TextField()),
                ('corpo', models.TextField()),
                ('inviata_il', models.DateTimeField(auto_now_add=True)),
                ('destinatari', models.ManyToManyField(related_name='email_destinatari', to='librosoci.Socio')),
                ('mittente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviata_il', models.DateTimeField(auto_now_add=True)),
                ('destinatari', models.ManyToManyField(related_name='remaindee', to='librosoci.Socio')),
                ('mittente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reminder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
