# Generated by Django 2.0.2 on 2018-05-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsamail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='destinatari',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='mittente',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
