# Generated by Django 2.0.2 on 2018-05-17 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elsausers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcredentials',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elsausers.UserProfile'),
        ),
    ]
