# Generated by Django 2.0.2 on 2018-05-17 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsausers', '0002_emailcredentials_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcredentials',
            name='name',
        ),
        migrations.RemoveField(
            model_name='emailcredentials',
            name='slug',
        ),
    ]
