# Generated by Django 2.0.2 on 2018-05-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsausers', '0004_auto_20180517_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailcredentials',
            old_name='e_user',
            new_name='e_username',
        ),
    ]
