# Generated by Django 2.0.2 on 2018-05-17 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elsausers', '0005_auto_20180517_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcredentials',
            name='e_host',
        ),
        migrations.RemoveField(
            model_name='emailcredentials',
            name='e_password',
        ),
        migrations.RemoveField(
            model_name='emailcredentials',
            name='e_port',
        ),
        migrations.RemoveField(
            model_name='emailcredentials',
            name='e_username',
        ),
        migrations.AddField(
            model_name='emailcredentials',
            name='host',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailcredentials',
            name='password',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailcredentials',
            name='port',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailcredentials',
            name='tls',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailcredentials',
            name='username',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailcredentials',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='elsausers.UserProfile'),
            preserve_default=False,
        ),
    ]
