# Generated by Django 2.0.2 on 2018-05-17 23:00

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elsausers', '0006_auto_20180517_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcredentials',
            name='password',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
    ]
