# Generated by Django 2.0.2 on 2018-05-22 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConsigliere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Email consigliere',
                'verbose_name_plural': 'Email consiglieri',
                'db_table': 'email_consiglieri',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmailConsigliere',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Email consigliere',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalRinnovoIscrizione',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_rinnovo', models.DateField()),
                ('quota_rinnovo', models.FloatField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Rinnovo iscrizione',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSezioneElsa',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Sezione ELSA',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSocio',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.TextField()),
                ('cognome', models.TextField()),
                ('numero_tessera', models.IntegerField()),
                ('codice_fiscale', models.TextField()),
                ('cellulare', models.TextField(blank=True, default='', null=True)),
                ('email', models.EmailField(max_length=254)),
                ('universita', models.TextField(blank=True, default='', null=True)),
                ('data_iscrizione', models.DateField()),
                ('quota_iscrizione', models.FloatField()),
                ('scadenza_iscrizione', models.DateField()),
                ('ultimo_rinnovo', models.DateField(blank=True, editable=False)),
                ('attivo', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(blank=True, editable=False)),
                ('subscribed', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Socio',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviata_il', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RinnovoIscrizione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rinnovo', models.DateField()),
                ('quota_rinnovo', models.FloatField()),
            ],
            options={
                'verbose_name': 'Rinnovo iscrizione',
                'verbose_name_plural': 'Rinnovi iscrizioni',
                'db_table': 'rinnovi',
            },
        ),
        migrations.CreateModel(
            name='RuoliSoci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consigliere_dal', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.TextField()),
                ('abbreviazione', models.TextField()),
            ],
            options={
                'verbose_name': 'Consigliere',
                'verbose_name_plural': 'Consiglieri',
                'db_table': 'ruoli_consiglieri',
            },
        ),
        migrations.CreateModel(
            name='SezioneElsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
            options={
                'verbose_name': 'Sezione ELSA',
                'verbose_name_plural': 'Sezioni ELSA',
                'db_table': 'sezioni_elsa',
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('cognome', models.TextField()),
                ('numero_tessera', models.IntegerField()),
                ('codice_fiscale', models.TextField()),
                ('cellulare', models.TextField(blank=True, default='', null=True)),
                ('email', models.EmailField(max_length=254)),
                ('universita', models.TextField(blank=True, default='', null=True)),
                ('data_iscrizione', models.DateField()),
                ('quota_iscrizione', models.FloatField()),
                ('scadenza_iscrizione', models.DateField()),
                ('ultimo_rinnovo', models.DateField(auto_now_add=True)),
                ('attivo', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('subscribed', models.BooleanField(default=True)),
                ('sezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librosoci.SezioneElsa')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Soci',
                'db_table': 'soci',
            },
        ),
        migrations.AddField(
            model_name='ruolo',
            name='soci',
            field=models.ManyToManyField(related_name='ruolo_socio', through='librosoci.RuoliSoci', to='librosoci.Socio'),
        ),
        migrations.AddField(
            model_name='ruolisoci',
            name='ruolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librosoci.Ruolo'),
        ),
        migrations.AddField(
            model_name='ruolisoci',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librosoci.Socio'),
        ),
        migrations.AddField(
            model_name='rinnovoiscrizione',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='librosoci.Socio'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='destinatari',
            field=models.ManyToManyField(related_name='remaindee', to='librosoci.Socio'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='mittente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reminder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsocio',
            name='sezione',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='librosoci.SezioneElsa'),
        ),
        migrations.AddField(
            model_name='historicalrinnovoiscrizione',
            name='socio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='librosoci.Socio'),
        ),
        migrations.AddField(
            model_name='historicalemailconsigliere',
            name='ruolo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='librosoci.Ruolo'),
        ),
        migrations.AddField(
            model_name='historicalemailconsigliere',
            name='socio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='librosoci.Socio'),
        ),
        migrations.AddField(
            model_name='emailconsigliere',
            name='ruolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librosoci.Ruolo'),
        ),
        migrations.AddField(
            model_name='emailconsigliere',
            name='socio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='librosoci.Socio'),
        ),
    ]
