# Generated by Django 2.0.2 on 2018-05-15 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librosoci', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RinnovoIscrizione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rinnovo', models.DateField()),
                ('quota_rinnovo', models.FloatField()),
            ],
            options={
                'db_table': 'rinnovi',
            },
        ),
        migrations.AddField(
            model_name='socio',
            name='attivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rinnovoiscrizione',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='librosoci.Socio'),
        ),
    ]
