# Generated by Django 2.0.2 on 2018-05-16 06:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('librosoci', '0003_socio_scadenza_iscrizione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consigliere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.TextField()),
            ],
            options={
                'db_table': 'ruoli_consiglieri',
            },
        ),
        migrations.CreateModel(
            name='ModificheSoci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('cognome', models.TextField()),
                ('data_di_nascita', models.DateField()),
                ('codice_fiscale', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('data_iscrizione', models.DateField()),
                ('scadenza_iscrizione', models.DateField()),
                ('attivo', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField()),
                ('dati_dal', models.DateTimeField()),
                ('dati_al', models.DateTimeField(auto_now_add=True)),
                ('ruolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='librosoci.Consigliere')),
                ('sezione', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='librosoci.SezioneElsa')),
            ],
        ),
        migrations.AddField(
            model_name='socio',
            name='data_creazione',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modifichesoci',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='librosoci.Socio'),
        ),
        migrations.AddField(
            model_name='socio',
            name='ruolo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='librosoci.Consigliere'),
        ),
    ]
