# Generated by Django 2.0.2 on 2018-05-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librosoci', '0005_auto_20180516_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifichesoci',
            name='ruolo',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='ruolo',
        ),
    ]
