# Generated by Django 2.0.2 on 2018-05-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librosoci', '0007_auto_20180516_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifichesoci',
            name='ruolo',
        ),
        migrations.RemoveField(
            model_name='modifichesoci',
            name='sezione',
        ),
        migrations.RemoveField(
            model_name='modifichesoci',
            name='socio',
        ),
        migrations.RemoveField(
            model_name='rinnovoiscrizione',
            name='socio',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='ruolo',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='sezione',
        ),
        migrations.DeleteModel(
            name='ModificheSoci',
        ),
        migrations.DeleteModel(
            name='RinnovoIscrizione',
        ),
        migrations.DeleteModel(
            name='Socio',
        ),
    ]
