# Generated by Django 2.0.2 on 2018-05-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librosoci', '0009_auto_20180516_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='numero_tessera',
            field=models.IntegerField(default=324567),
            preserve_default=False,
        ),
    ]
