# Generated by Django 2.0.2 on 2018-05-16 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('librosoci', '0010_socio_numero_tessera'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='ultimo_rinnovo',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
