# Generated by Django 2.0.2 on 2018-05-16 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librosoci', '0012_socio_consigliere_dal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConsigliere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ruolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librosoci.Consigliere')),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='librosoci.Socio')),
            ],
        ),
    ]
