# Generated by Django 2.0.2 on 2018-05-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librosoci', '0014_auto_20180516_0832'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailconsigliere',
            table='email_consiglieri',
        ),
    ]
