# Generated by Django 2.0.2 on 2018-05-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librosoci', '0015_auto_20180516_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consigliere',
            options={'verbose_name': 'Consigliere', 'verbose_name_plural': 'Consiglieri'},
        ),
        migrations.AlterModelOptions(
            name='emailconsigliere',
            options={'verbose_name': 'Email consigliere', 'verbose_name_plural': 'Email consiglieri'},
        ),
        migrations.AlterModelOptions(
            name='modifichesoci',
            options={'verbose_name': 'Modifica socio', 'verbose_name_plural': 'Modifiche soci'},
        ),
        migrations.AlterModelOptions(
            name='rinnovoiscrizione',
            options={'verbose_name': 'Rinnovo iscrizione', 'verbose_name_plural': 'Rinnovi iscrizioni'},
        ),
        migrations.AlterModelOptions(
            name='sezioneelsa',
            options={'verbose_name': 'Sezione ELSA', 'verbose_name_plural': 'Sezioni ELSA'},
        ),
        migrations.AlterModelOptions(
            name='socio',
            options={'verbose_name': 'Socio', 'verbose_name_plural': 'Soci'},
        ),
        migrations.AlterModelTable(
            name='modifichesoci',
            table='modifiche_soci',
        ),
    ]
