# Generated by Django 2.0.2 on 2018-05-16 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('librosoci', '0016_auto_20180516_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='sezioneelsa',
            old_name='citta',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='consigliere',
            name='sezione',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='librosoci.SezioneElsa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sezioneelsa',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socio',
            name='sezione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librosoci.SezioneElsa'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sezione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librosoci.SezioneElsa'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
