# Generated by Django 2.0.2 on 2018-05-16 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librosoci', '0017_auto_20180516_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consigliere',
            name='sezione',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sezione',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='librosoci.SezioneElsa'),
        ),
    ]
