# Generated by Django 2.0.2 on 2018-05-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librosoci', '0018_auto_20180516_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='data_di_nascita',
        ),
    ]
