# Generated by Django 2.0.2 on 2018-05-17 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librosoci', '0019_remove_socio_data_di_nascita'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModificheRinnovoSoci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rinnovo', models.DateField()),
                ('quota_rinnovo', models.FloatField()),
                ('rinnovo_iscrizione', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='librosoci.RinnovoIscrizione')),
            ],
            options={
                'verbose_name': 'Modifica rinnovo iscrizione',
                'verbose_name_plural': 'Modifiche rinnovi iscrizioni',
                'db_table': 'modifiche_rinnovi',
            },
        ),
        migrations.AlterField(
            model_name='emailconsigliere',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='librosoci.Socio'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='ruolo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='librosoci.Consigliere'),
        ),
        migrations.AddField(
            model_name='modificherinnovosoci',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='librosoci.Socio'),
        ),
    ]
