# Generated by Django 2.0.2 on 2018-05-17 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librosoci', '0020_auto_20180517_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconsigliere',
            name='socio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='librosoci.Socio'),
        ),
    ]
