# Generated by Django 2.0.2 on 2018-05-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librosoci', '0021_auto_20180517_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifichesoci',
            name='quota_iscrizione',
            field=models.FloatField(default=10.0),
            preserve_default=False,
        ),
    ]
