# Generated by Django 2.0.2 on 2018-05-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librosoci', '0024_auto_20180517_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsocio',
            name='consigliere_dal',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalsocio',
            name='data_iscrizione',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalsocio',
            name='scadenza_iscrizione',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='socio',
            name='consigliere_dal',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='data_iscrizione',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='socio',
            name='scadenza_iscrizione',
            field=models.DateTimeField(),
        ),
    ]
