# Generated by Django 2.0.2 on 2018-05-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librosoci', '0025_auto_20180517_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsocio',
            name='consigliere_dal',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalsocio',
            name='data_iscrizione',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalsocio',
            name='scadenza_iscrizione',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='socio',
            name='consigliere_dal',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='data_iscrizione',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='socio',
            name='scadenza_iscrizione',
            field=models.DateField(),
        ),
    ]
