# Generated by Django 2.0.2 on 2018-05-17 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('librosoci', '0026_auto_20180517_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSezioneElsa',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Sezione ELSA',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='sezione',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sezione',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalUserProfile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
